.github/workflows/trivy.yml
Makefile
controllers/daemon/staticgatewayconfiguration_controller_test.go
controllers/manager/gatewaylbconfiguration_controller_test.go
docker/cnimanager.Dockerfile
docker/gwdaemon.Dockerfile
pkg/azmanager/azmanager_test.go

add trivy workflow

---

controllers/manager/gatewayvmconfiguration_controller.go
controllers/manager/gatewayvmconfiguration_controller_test.go

Fix error found in e2e tests. There's a chance that, after `vmConfig` deletion is reconciled and `vmConfig` finalizer is removed, the next list `vmConfig` can still read this `vmConfig` and it's reconciled again...

fix: avoid reconciling deleting vmConfig upon node event

---

.github/workflows/main.yml

Auto approve dependabot prs

---

controllers/daemon/staticgatewayconfiguration_controller.go

Gateway mgr daemon needs to watch GatewayVMConfiguration objects also.

fix: fix daemon reconcile bug during node upgrade

---

README.md

Add a note about operating system support to the readme file.

Add information about operating system support.

---

cmd/kube-egress-gateway-controller/cmd/root.go
pkg/azmanager/azmanager.go
pkg/azmanager/azmanager_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/consts/const.go

/kind feature
Apply loadshedding to ARM clients
1. Apply 60s timeout for all ARM requests.
2. Add ratelimiter configuration.
3. Retries and throttling are natively builtin with controller-runtime and azclient.
Fixes #

loadshedding for arm clients

---

.github/workflows/trivy.yml

/kind cleanup
upload trivy result to github security
Fixes #

upload trivy result to github security

---

config/cnimanager/rbac/role.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_gatewaylbconfigurations.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_gatewaystatuses.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_gatewayvmconfigurations.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_podendpoints.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_staticgatewayconfigurations.yaml
config/daemon/rbac/role.yaml
config/manager/rbac/role.yaml
go.mod
go.sum
pkg/cni/routes/routes.go
pkg/cni/routes/routes_test.go

fix build error from netlink upgrade

---

cmd/kube-egress-gateway-controller/cmd/root.go
go.mod
go.sum

/kind cleanup
Chores: adopt new authprovider 
Fixes #

Chores: adopt new authprovider 

---

.github/workflows/trivy.yml

Chores:run trivy on main branch
Fixes #

Chores:run trivy on main branch

---

.github/dependabot.yml

/kind cleanup
Ignore sdk update to keep apiversion aligned with azclient package.
Fixes #

Ignore sdk update to keep apiversion aligned with azclient package.

---

docker/base.Dockerfile
docker/cni.Dockerfile
docker/cnimanager.Dockerfile
docker/gwdaemon.Dockerfile

/kind cleanup
fix pinned dependencies in dockerfile
Fixes #

fix pinned dependencies in dockerfile

---

.github/dependabot.yml

/kind cleanup
Group all deps update into one pr
Fixes #

Group all deps update into one pr

---

.pipeline/e2e.yaml
docker/base.Dockerfile
go.mod

/kind cleanup
Bump to go version 1.23.7 as with #999 
Fixes #

bump go version to 1.23.7

---

go.mod
hack/generate_release_note.sh

/kind feature
add shell script to help generate release note;
add replace for those dependencies that kubernetes introduces as private modules. generate_release_note.sh executes `go list -m all` to help compare the imported modules between 2 releases. `go list -m all` will fail without these replace.
Fixes #

chore: add generate_release_note.sh

---

pkg/config/config.go
pkg/config/config_test.go
pkg/consts/const.go

/kind cleanup
chore: remove default rate limiting as it is not required with new Azure clients and may cause clients too slow.
Fixes #

chore: remove default rate limiting

---

.pipeline/e2e.yaml
e2e/e2e_test.go
hack/run_e2e.sh
pkg/azmanager/azmanager.go

/kind bug
add longer timeout for deleting public IP prefix
Fixes #

fix: add longer timeout for deleting public IP prefix

---

config/crd/bases/egressgateway.kubernetes.azure.com_gatewaylbconfigurations.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_gatewaystatuses.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_gatewayvmconfigurations.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_podendpoints.yaml
config/crd/bases/egressgateway.kubernetes.azure.com_staticgatewayconfigurations.yaml
config/daemon/rbac/role.yaml
config/manager/rbac/role.yaml
config/manager/rbac/role_binding.yaml
controllers/daemon/staticgatewayconfiguration_controller.go
controllers/manager/staticgatewayconfiguration_controller.go
helm/kube-egress-gateway/Chart.yaml
helm/kube-egress-gateway/templates/gateway-controller-manager.yaml

Reverts Azure/kube-egress-gateway#1053

Revert "chore: move secret related permissions to seperate Role"

---

.github/workflows/build-and-pusblish-mcr.yml
.github/workflows/build.yml
Makefile
config/daemon/manager/manager.yaml
docker/docker-bake.hcl
docker/docker-localtag-bake.hcl
docker/gwdaemon-init.Dockerfile
helm/kube-egress-gateway/templates/_helpers.tpl
helm/kube-egress-gateway/templates/gateway-daemon-manager.yaml
helm/kube-egress-gateway/values.yaml

/kind feature
/kind enhancement
add image build & publish for deamon manager's init container
Fixes #

build: build image for daemon manager init container

---

.github/workflows/build.yml
.pipeline/e2e.yaml
cmd/add-netns/main.go
cmd/add-netns/main_test.go
cmd/copy/main.go
cmd/copy/main_test.go
docker/cni-ipam.Dockerfile
docker/cni.Dockerfile
docker/docker-bake.hcl
docker/gwdaemon-init.Dockerfile

add golang executable as entrypoint & replace base images to distroless for cni manager & daemon manager's init container
Fixes #

chore: add golang executable as entrypoint & replace base images to distroless

---

cmd/kube-egress-cni/main.go

/kind bug
Fix: ignore deletion error and log error into stderr
Fixes #759

Fix: ignore deletion error and log error into stderr

---

controllers/manager/gatewayvmconfiguration_controller.go
e2e/e2e_test.go
go.mod
pkg/azmanager/azmanager.go
pkg/azmanager/azmanager_test.go

/kind enhancement
/kind failing-test
add retry for retriable Azure resource operations;
fix flaky e2e test;
Fixes #

add retry for Azure resource operations

---

config/cnimanager/daemon/cnimanager.yaml
config/manager/manager/manager.yaml
pkg/azmanager/azmanager.go

fix: set bigger memory limit for cni manager & controller

---

.pipeline/e2e.yaml

/kind bug
/kind failing-test
Fix E2E pipeline.
Fixes #

Fix E2E pipeline

---

.pipeline/e2e.yaml
.pipeline/templates/e2e-steps.yml

/kind feature
runs multiple cni types as part of e2e

build: run overlay and nodesubnet (flat network) e2e tests
